export enum FinancialTransactionErrorType {
    NO_ERROR = "NO_ERROR",
    UNKNOW_ERROR = "UNKNOW_ERROR",
    INSUFFICIENT_AMOUNT_ERROR = "INSUFFICIENT_AMOUNT_ERROR",
    INVALID_PHONE_NUMBER = "INVALID_PHONE_NUMBER",
    RECEIVER_NOT_FOUND_ERROR = "RECEIVER_NOT_FOUND_ERROR",
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR" // Ajout de cette valeur
}