
export enum StrategyResponseStatus
{
    SUCCESSFUL="SUCCESSFULL",
    FAILED="FAILED",
    PAYER_NOT_FOUND="PAYER_NOT_FOUND",
    PAYEE_NOT_FOUND="PAYEE_NOT_FOUND",
    PENDING="PENDING",
    EXPIRED="EXPIRED",
    CANCELLED="CANCELLED"
}